logging:
  pattern:
    console: '%d{"yyyy-MM-dd HH:mm:ss"} [%p] [%4.4t] (%30.30F:%4.4L\) - [%X{user}@%X{ip}] %m%n'
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    dispatch-options-request: true
  data:
    mongodb:
      uri: ${BILIOB_MONGO_URL}
  mail:
    host: smtp.gmail.com
    password: ${BILIOB_MAIL_PASSWORD}
    username: noreply@bilibili.dog
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            fallback: false
            class: javax.net.ssl.SSLSocketFactory
          starttls.enable: true
          auth: true
          ssl:
            enable: true
server:
  port: ${BILIOB_BACKEND_PORT}
  servlet:
    session:
      cookie:
        max-age: 86400000000